### PR TITLE
[WIP] Truffle tests race condition

### LINKED ISSUE #16: Race condition in truffle test
There's a bug in truffle test that makes our tests fail randomly, fixing it is of utmost importance due to hugely increased rates of circleci tests failing.

### PR DESCRIPTION
**Pull request by ritave**
Possibly remove the race issue in truffle, or at least decrease it's occurence
fix #16

### CODE REVIEW

File: packages/contracts/truffle-config.js [hunk 1]
```diff
@@ -3,20 +3,16 @@ module.exports = {
...
-      mochaJunitReporterReporterOptions: {
-        mochaFile: './build/junit/junit.xml'
-      }
-    }
-  },
   networks: {
     develop: {
       host: "localhost",
-      port: 9545,
+      port: 8545,
```
Comment (nickreynolds) [inline packages/contracts/truffle-config.js]: I specifically had to make this 9545 for it to work with `truffle develop`, it's working at 8545?

Comment (ritave) [reply packages/contracts/truffle-config.js]: Just checked, seems so
